version: "3"
services:
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: pandawithcat/flower_classification_client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    image: pandawithcat/flower_classification_api
    volumes:
      - /app/env
      - ./server:/app
